[general]
live_config_reload = true

[font]
size = 11
offset.x = -1
# offset.y = -1
offset.y = -2

[font.normal]
# family = "Comic Mono"
# family = "MesloLGS Nerd Font Mono"
# family = "RobotoMono Nerd Font Mono"
# family = "ComicShannsMono Nerd Font"
family = "JetBrainsMono Nerd Font Mono"
# family = "Fira Code"
# family = "SF Mono"
# family = "Commit Mono Nerd Font"
# family = "Hack Nerd Font"
# family = "ComicShanns Mono Nerd Font"
# family = "Ubuntu Mono Nerd Font"
# family = "Hack"
# family = "Menlo Nerd Font Mono"
# style = "semibold"
style = "bold"

[window]
# opacity = 0.95
# title = "Terminal"
# startup_mode = "Windowed"
dimensions = { columns = 110, lines = 40 }
padding = { x = 2, y = 2 }
dynamic_title = true
# decorations = "none"

[cursor]
style = { blinking = "Always" }
blink_interval = 300

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
# background = "0x1d2021"
background = "0x17191A"
foreground = "0xebdbb2"

[env]
TERM = "alacritty"

[scrolling]
history = 100000
multiplier = 10

